"""Puertos (interfaces) que el dominio necesita del mundo exterior.

La infraestructura los implementa (SQLite, disco, JWT…). Cambiar SQLite por
PostgreSQL = escribir otra clase que cumpla estos contratos; nada más cambia.
"""
from __future__ import annotations

from datetime import datetime
from typing import BinaryIO, Protocol

from .entidades import Aliado, Archivo, GrupoAliados, Item, Seccion, Usuario


class RepositorioUsuarios(Protocol):
    def por_id(self, usuario_id: int) -> Usuario | None: ...
    def por_usuario(self, usuario: str) -> Usuario | None: ...
    def listar(self) -> list[Usuario]: ...
    def guardar(self, usuario: Usuario) -> Usuario: ...
    def guardar_varios(self, usuarios: list[Usuario]) -> list[Usuario]: ...
    def eliminar(self, usuario_id: int) -> None: ...
    def registrar_login(self, usuario_id: int, momento: datetime) -> None: ...


class RepositorioSecciones(Protocol):
    def por_id(self, seccion_id: int) -> Seccion | None: ...
    def listar(self, solo_activas: bool = False) -> list[Seccion]: ...
    def guardar(self, seccion: Seccion) -> Seccion: ...
    def eliminar(self, seccion_id: int) -> None: ...
    def reordenar(self, ids_en_orden: list[int]) -> None: ...
    def siguiente_orden(self) -> int: ...


class RepositorioItems(Protocol):
    def por_id(self, item_id: int) -> Item | None: ...
    def de_seccion(self, seccion_id: int, solo_activos: bool = False) -> list[Item]: ...
    def de_secciones(self, seccion_ids: list[int], solo_activos: bool = False) -> list[Item]: ...
    def guardar(self, item: Item) -> Item: ...
    def eliminar(self, item_id: int) -> None: ...
    def reordenar(self, seccion_id: int, ids_en_orden: list[int]) -> None: ...
    def siguiente_orden(self, seccion_id: int) -> int: ...
    def archivo_visible_para_participantes(self, archivo_id: int) -> bool: ...


class RepositorioArchivos(Protocol):
    def por_id(self, archivo_id: int) -> Archivo | None: ...
    def por_ids(self, ids: list[int]) -> dict[int, Archivo]: ...
    def guardar(self, archivo: Archivo) -> Archivo: ...
    def eliminar(self, archivo_id: int) -> None: ...
    def huerfanos(self) -> list[Archivo]: ...


class RepositorioAjustes(Protocol):
    """Valores sueltos de configuración del evento (por ejemplo, el logo)."""
    def obtener(self, clave: str) -> str | None: ...
    def fijar(self, clave: str, valor: str | None) -> None: ...


class RepositorioAliados(Protocol):
    def grupos(self) -> list[GrupoAliados]: ...
    def grupo_por_id(self, grupo_id: int) -> GrupoAliados | None: ...
    def guardar_grupo(self, grupo: GrupoAliados) -> GrupoAliados: ...
    def eliminar_grupo(self, grupo_id: int) -> None: ...
    def reordenar_grupos(self, ids_en_orden: list[int]) -> None: ...
    def siguiente_orden_grupo(self) -> int: ...
    def aliados(self) -> list[Aliado]: ...
    def aliado_por_id(self, aliado_id: int) -> Aliado | None: ...
    def guardar_aliado(self, aliado: Aliado) -> Aliado: ...
    def eliminar_aliado(self, aliado_id: int) -> None: ...
    def reordenar_aliados(self, grupo_id: int, ids_en_orden: list[int]) -> None: ...
    def siguiente_orden_aliado(self, grupo_id: int) -> int: ...


class AlmacenArchivos(Protocol):
    def guardar(self, flujo: BinaryIO, extension: str) -> tuple[str, int]: ...
    def ruta(self, nombre_guardado: str) -> str: ...
    def miniatura(self, nombre_guardado: str) -> str | None: ...
    def eliminar(self, nombre_guardado: str) -> None: ...


class RegistroActividad(Protocol):
    def registrar(self, tipo: str, usuario_id: int, referencia_id: int | None = None) -> None: ...
    def resumen(self) -> dict: ...


class ControlIntentos(Protocol):
    def fallos_recientes(self, clave: str, ventana_segundos: int) -> int: ...
    def registrar_fallo(self, clave: str) -> None: ...
    def limpiar(self, clave: str) -> None: ...


class HasherContrasenas(Protocol):
    def hashear(self, contrasena: str) -> str: ...
    def verificar(self, contrasena: str, hash_guardado: str) -> bool: ...


class EmisorTokens(Protocol):
    def emitir(self, usuario: Usuario) -> str: ...
    def leer(self, token: str) -> dict: ...


class Reloj(Protocol):
    def ahora(self) -> datetime: ...
